import { WorkOrder } from "./types";

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: "#11",
    title: "Change a faucet",
    requestedBy: "Margaret Ruga",
    status: "done",
    priority: "medium",
    dueDate: "05/12/2026",
    overdue: false,
    description:
      "Replace a faucet in kitchen area. Check for leaks after installation and run water for 10 minutes to confirm seal integrity.",
    asset: "Kitchen Sink Unit",
    location: "Location B — Kitchen",
    assignees: [
      { initials: "GG", name: "Giselle Georges", color: "blue" },
      { initials: "JH", name: "Jermaine Harriott", color: "green" },
    ],
    checklist: [
      { label: "Turn off water supply", done: true },
      { label: "Remove old faucet", done: true },
      { label: "Install new faucet", done: true },
      { label: "Test for leaks", done: true },
    ],
    completedOn: "06/15/2026",
    category: "Plumbing",
  },
  {
    id: "#13",
    title: "Light replacement",
    requestedBy: "Margaret Ruga",
    status: "open",
    priority: "low",
    dueDate: "06/10/2026",
    overdue: true,
    description:
      "Replace fluorescent tube in dining area. Use LED equivalent (4000K). Dispose of old tube per hazmat protocol.",
    asset: "Dining Area Ceiling",
    location: "Zone C — Dining",
    assignees: [{ initials: "MR", name: "Margaret Ruga", color: "amber" }],
    checklist: [
      { label: "Purchase LED tube (4000K)", done: true },
      { label: "Switch off breaker", done: false },
      { label: "Replace tube", done: false },
      { label: "Restore power and test", done: false },
    ],
    category: "Electrical",
  },
  {
    id: "#7",
    title: "ICE machine servicing",
    requestedBy: "Margaret Ruga",
    status: "in_progress",
    priority: "high",
    dueDate: "06/05/2026",
    overdue: true,
    description:
      "Full service of ice machine. Clean condenser, check refrigerant level, sanitize ice bin, replace water filter.",
    asset: "Ice Machine Unit",
    location: "Bar Area — Level 1",
    assignees: [
      { initials: "JH", name: "Jermaine Harriott", color: "green" },
      { initials: "GG", name: "Giselle Georges", color: "blue" },
    ],
    checklist: [
      { label: "Defrost machine", done: true },
      { label: "Clean condenser coils", done: true },
      { label: "Check refrigerant", done: false },
      { label: "Replace water filter", done: false },
      { label: "Run test cycle", done: false },
    ],
    category: "HVAC / Refrigeration",
  },
  {
    id: "#15",
    title: "Grease trap cleaning",
    requestedBy: "Carlos Mendez",
    status: "open",
    priority: "high",
    dueDate: "06/18/2026",
    overdue: false,
    description:
      "Monthly grease trap cleaning and inspection. Document waste volume. Arrange certified disposal.",
    asset: "Grease Trap — Main Kitchen",
    location: "Kitchen — Basement",
    assignees: [{ initials: "CM", name: "Carlos Mendez", color: "purple" }],
    checklist: [
      { label: "Prepare PPE and equipment", done: false },
      { label: "Pump and clean trap", done: false },
      { label: "Inspect baffles", done: false },
      { label: "Log waste volume", done: false },
    ],
    category: "Sanitation",
  },
  {
    id: "#9",
    title: "HVAC filter replacement",
    requestedBy: "Giselle Georges",
    status: "on_hold",
    priority: "medium",
    dueDate: "06/20/2026",
    overdue: false,
    description:
      "Quarterly HVAC filter change across all units. Waiting on parts delivery — filters on back-order until 06/17.",
    asset: "HVAC System",
    location: "Roof — All Units",
    assignees: [
      { initials: "JH", name: "Jermaine Harriott", color: "green" },
    ],
    checklist: [
      { label: "Confirm parts delivery", done: false },
      { label: "Schedule access to roof", done: true },
      { label: "Replace filters (8 units)", done: false },
      { label: "Log serial numbers", done: false },
    ],
    category: "HVAC / Refrigeration",
  },
];